import 'package:equatable/equatable.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:thrill_quest/app/constant/hive/hive_table_constant.dart';
import 'package:thrill_quest/features/bookings/domain/entity/bookings_entity.dart'; // Import your BookingsEntity
import 'package:uuid/uuid.dart'; // For generating unique IDs if needed

part 'bookings_hive_model.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: HiveTableConstant.bookingsTableId)
class BookingsHiveModel extends Equatable {
  @HiveField(0)
  final String? bookingId; // Use bookingId for clarity, similar to userId

  @HiveField(1)
  final String activityId;

  @HiveField(2)
  final String customerName;

  @HiveField(3)
  final String guideName;

  @HiveField(4)
  final DateTime tourDate;

  @HiveField(5)
  final String paymentStatus;

  @HiveField(6)
  final String bookingStatus;

  @HiveField(7)
  final String userId;

  @HiveField(8)
  final DateTime createdAt;

  @HiveField(9)
  final DateTime updatedAt;

  BookingsHiveModel({
    String? bookingId, // Make optional for new bookings
    required this.activityId,
    required this.customerName,
    required this.guideName,
    required this.tourDate,
    required this.paymentStatus,
    required this.bookingStatus,
    required this.userId,
    required this.createdAt,
    required this.updatedAt,
  }) : bookingId =
           bookingId ?? const Uuid().v4(); // Generate ID if not provided

  // Convert from BookingsEntity to BookingsHiveModel
  factory BookingsHiveModel.fromEntity(BookingsEntity entity) {
    return BookingsHiveModel(
      bookingId: entity.id, // Use entity.id for existing bookings
      activityId: entity.activityId,
      customerName: entity.customerName,
      guideName: entity.guideName,
      tourDate: entity.tourDate,
      paymentStatus: entity.paymentStatus,
      bookingStatus: entity.bookingStatus,
      userId: entity.userId,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    );
  }

  // Convert from BookingsHiveModel to BookingsEntity
  BookingsEntity toEntity() {
    return BookingsEntity(
      id:
          bookingId ??
          '', // Provide a default empty string if bookingId is null
      activityId: activityId,
      customerName: customerName,
      guideName: guideName,
      tourDate: tourDate,
      paymentStatus: paymentStatus,
      bookingStatus: bookingStatus,
      userId: userId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  @override
  List<Object?> get props => [
    bookingId,
    activityId,
    customerName,
    guideName,
    tourDate,
    paymentStatus,
    bookingStatus,
    userId,
    createdAt,
    updatedAt,
  ];
}
